### ISSUE TITLE
yarnInstall being called multiple times

### ISSUE THREAD

**Issue by Roms1383** [yeoman/yeoman#1711] opened 2019-06-01 10:22 UTC
## Context

Documentation on [Managing dependencies](https://yeoman.io/authoring/dependencies.html) states that : 
> You just need to call this.yarnInstall() to launch the installation. Yeoman will ensure the yarn install command **is only run once even if it is called multiple time by multiple generators**.

## Issue
When installing dependencies, `yarnInstall` triggers multiple calls to `yarn install ...`

## Test
In order to reproduce, you can check my [repo at v1.3.0](https://github.com/Roms1383/generator-kroms/releases/tag/v1.3.0)

1. Checkout
```bash
git clone https://github.com/Roms1383/generator-kroms.git
```
2. Switch to v1.3.0
```bash
git checkout v1.3.0
```
3. Link
```bash
yarn link
```
4. Launch
```bash
yo kroms
```

And the result is :
<img width="778" alt="Screen Shot 2562-06-01 at 17 18 12" src="https://user-images.githubusercontent.com/21016014/58747151-48eb1100-8491-11e9-87b4-80ae45f0e05c.png">

When it would be expected to only have a single `yarn install ...` running.

**Comment by fernandopasik** [comment] 2019-07-22 22:04
I've noticed the same problem

**Comment by mshima** [comment] 2020-01-31 03:13
Yarn and npm are executed once per full command. Once 'npm', once 'npm -dev'
https://github.com/yeoman/generator/blob/006e13e485fcaeed613c78d594884bc1c69961e5/lib/actions/install.js#L91

Looks like each generator install dependencies for itself. Making them different.

Closing as this is not a bug.

**Closed by mshima** 2020-01-31 03:13 UTC
Labels: bug
