### ISSUE TITLE
Bootstrap still missing when using yo angular

### ISSUE THREAD

**Issue by nigel-dewar** [yeoman/yeoman#1513] opened 2015-06-19 05:42 UTC
This has not been fixed. Bootstrap still missing.

**Comment by arthurvr** [comment] 2015-06-19 10:26
Duplicate of https://github.com/yeoman/generator-angular/issues/1116.

**Closed by arthurvr** 2015-06-19 10:26 UTC

**Comment by sdbeng** [comment] 2015-07-23 18:40
I'm still having issues. No bootstrap css link present. Using latest version of angular-generator. Will try temp fixes for now.(downgrading)
