### ISSUE TITLE
Yeoman doesn't solve the problem very well

### ISSUE THREAD

**Issue by stringa** [yeoman/yeoman#1489] opened 2015-02-28 00:04 UTC
I messed around with Yeoman last night for multiple hours.  What I was looking to do was get the scaffolding of the app that I want to build up and running as quick as possible.  My first problem is that when I download these packages, I just don't have a lot of information on the packages.  There is no description about the package other than the name and sometimes I am guessing and hoping that the package contains something other than what is in the name.  Next, many of the generators don't really seem to work that well.  I had a lot of problems with packages that had "options" to work properly after the download.  I know this isn't a problem of Yeoman, but it may state something about the design.  Maybe that Yeoman is trying to be too general.  

I wanted a project of the following:
Node.JS Server w/Express, HandleBars (Client and Server), EmberJS with Bootstrap.  Also, I wanted all the buildtools goodness that I see in the basic webapp package.  I was able to find a package that does most of this, but turns out it failed to install the package properly.  It seems that there is no verification process for these tools and no quality standard to release new generators.  I eventually started looking for other tools that try to do similar things.

Another thing I noticed is that packages don't really work together, they can, but they don't have to.  Again, this seems to be how it was designed.

What I will end up doing is download the basic 'generator-webapp' template and getting all the client build-tool goodness and then adding in everything else that I want.  This seems to be the only way I can get what I want.  This is so frustrating because I feel like this tool is suppose to solve that problem, but it just fell so short of that.

I feel like this tool is trying to be so general that it renders itself almost useless.

**Comment by Munter** [comment] 2015-02-28 08:33
Being able to combine generators is a work in progress, and pretty much the only way to solve your needs and the millions of other combinations of needs that people expect to be solved magically by one single tool.

What might be beneficial in the mean time would be to create a reference implementation of the things you need from your setup and open source it as a yeoman generator. That would give future reference for what details need to be covered

**Comment by eddiemonge** [comment] 2015-04-24 19:24
We appreciate the honest and open feedback. Yeoman has changed over the 3 years its been active. Like how the original Twitter was very different than it has become because of how users have shaped it, so to has Yeoman. People are doing things we didn't envision and were such good ideas that we are now trying to incorporate those to make a better tool. 

One of the biggest areas of focus has been around composability. It hasn't been the smoothest road but it is at a much better point now. Its up to the generator authors to update to use the newest changes. However, being that there are thousands of generators (must be doing something right to get to those numbers) updating them is a far bigger task then the Core and Contributors teams can do on their own.

Again, thanks for the feedback. I am closing this issue as it is not a bug report per se but feel free to keep the communication open and reporting your feedback.

**Closed by eddiemonge** 2015-04-24 19:24 UTC
