### ISSUE TITLE
yo can't find installed generators on Windows 7

### ISSUE THREAD

**Issue by seglo** [yeoman/yeoman#1463] opened 2015-01-08 14:49 UTC
I'm trying to use the `generator-angular-fullstack` generator to bootstrap a project, but yeoman can't seem to find my installed generator.

```
C:\source\crm>npm -v
1.4.28

C:\source\crm>node -v
v0.10.35

C:\source\crm>yo -v
1.4.0

C:\source\crm>npm list -g --depth=0
C:\Users\sglover\AppData\Roaming\npm
├── generator-angular-fullstack@2.0.13
└── yo@1.4.0

C:\source\crm>npm -g root
C:\Users\sglover\AppData\Roaming\npm\node_modules

C:\source\crm>dir C:\Users\sglover\AppData\Roaming\npm\node_modules
 Volume in drive C has no label.
 Volume Serial Number is 6CCD-B02A

 Directory of C:\Users\sglover\AppData\Roaming\npm\node_modules

01/08/2015  09:34 AM    <DIR>          .
01/08/2015  09:34 AM    <DIR>          ..
01/08/2015  09:34 AM    <DIR>          generator-angular-fullstack
01/08/2015  09:33 AM    <DIR>          yo
               0 File(s)              0 bytes
               4 Dir(s)  146,832,891,904 bytes free

C:\source\crm>yo --help
Usage: yo GENERATOR [args] [options]

General options:
  -h, --help     # Print generator's options and usage
  -f, --force    # Overwrite files that already exist


C:\source\crm>yo doctor
[Yeoman Doctor] Everything looks all right!
```
When I attempt to use the generator:
```
C:\source\crm>yo angular-fullstack
Error angular-fullstack

You don't seem to have a generator with the name angular-fullstack installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 16 registered generators run yo with the `--help` option.
```

Any ideas?

**Comment by sindresorhus** [comment] 2015-01-08 14:52
Duplicate of https://github.com/yeoman/yo/issues/264

**Closed by sindresorhus** 2015-01-08 14:52 UTC

**Comment by seglo** [comment] 2015-01-08 14:56
I downloaded `yo@1.3.3` and it's working.  Thanks.
