### ISSUE TITLE
HTTPS support on homepage

### ISSUE THREAD

**Issue by dfuentes77** [yeoman/yeoman#1677] opened 2017-09-26 22:15 UTC
In accordance with https://www.eff.org/https-everywhere

**Comment by SBoudrias** [comment] 2017-09-27 03:31
gh pages supports https now, we can totally do that now: https://help.github.com/articles/securing-your-github-pages-site-with-https/

Just need to make sure we don't get mixed content bugs when we turn it on.

**Comment by mischah** [comment] 2017-10-27 12:16
> HTTPS is not supported for GitHub Pages using custom domains.

😞 

Closing this since it’s a duplicate of https://github.com/yeoman/yeoman.github.io/issues/529

**Closed by mischah** 2017-10-27 12:16 UTC
