### ISSUE TITLE
composeWith sub-generator not mocking as expected

### ISSUE THREAD

**Issue by wulfgarpro** [yeoman/yeoman#1706] opened 2019-02-22 22:00 UTC
I'm trying to test my generator, which, using composeWith, relies on a sub-generator (generator-express):
```javascript
this.composeWith(require.resolve('generator-express/app'), {dirname: this.props.app_name, createDirectory: 'n'});
My test is trying to mock said sub-generator:

var deps = [
      [helpers.createDummyGenerator(), require.resolve('generator-express/app')]
];

describe('generator-cesium/app Test', () => {
    beforeEach(() => {
        return helpers.run(path.join(__dirname, '../generators/app'))
            .inDir(path.join(__dirname, 'tmp'))
            .withPrompts({
                viewerContext: '/',  // eslint-disable-line camelcase
                appName: 'app'       // eslint-disable-line camelcase
            })
            .withGenerators(deps)
    });
...
```

But, I keep getting the following error:
```bash
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (TypeError: Cannot read property 'match' of undefined)

      at Immediate.setImmediate (node_modules/generator-express/node_modules/yeoman-generator/lib/index.js:406:18)
```

The error, indicating that the sub-generator is still being executed, leads me to believe that the mock is not actually working?

**Comment by chippawah** [comment] 2019-03-02 00:26
I'm having the same issue. There's a command that's being run within the sub-generator that should be mocked and therefore not run.

**Comment by wulfgarpro** [comment] 2019-03-03 07:52
I have a running comentary on the problem [here](https://stackoverflow.com/questions/54839685/composewith-sub-generator-not-mocking-as-expected) on SO.  AFAICT, the only answer I've been given, as light on detail as it is, does not work and the [user who's answered](https://stackoverflow.com/users/1024223/simon-boudrias) purports to be a contributor to the Yeoman project 😟.

**Comment by eddiemonge** [comment] 2019-09-05 20:37
@wulfgarpro @SBoudrias is one of the core contributors and wrote the sub-generator stuff.

**Comment by mshima** [comment] 2020-01-31 02:57
The problem is that when you composeWith a generator path, it will load that path and ignore the registered generators/mocks.
https://github.com/yeoman/generator/blob/006e13e485fcaeed613c78d594884bc1c69961e5/lib/index.js#L707-L709

The mock is registered to the environment with the namespace.
To use the mock you should use namespaces instead of paths.

As far as I can see this is not a bug so I am closing it.

**Closed by mshima** 2020-01-31 02:57 UTC
