### ISSUE TITLE
YO, we have a problem

### ISSUE THREAD

**Issue by dimd13** [yeoman/yeoman#1500] opened 2015-04-11 11:21 UTC
1
```
npm install -g yo bower gulp
yo --version && echo $PATH $NODE_PATH && node -e 'console.log(process.platform, process.versions)'
```

1.4.6
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
linux { http_parser: '2.3',
  node: '0.12.0',
  v8: '3.28.73',
  uv: '1.0.2',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1l' }

2 
```
npm i -g generator-angular
```
3
```
yo angular
```
and catch this:

```
/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:74
				throw err;
				      ^
Error: EACCES, permission denied '/home/dimd13/.config/configstore/insight-yo.yml'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:502:18)
    at Object.fs.writeFileSync (evalmachine.<anonymous>:1103:15)
    at Object.create.all.set (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:64:8)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:27:11)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:36:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:117:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

```
**Error: EACCES, permission denied '/home/dimd13/.config/configstore/insight-yo.yml'
You don't have access to this file.**

but here is no insight-yo.yml file in /home/dimd13/.config/configstore

With others generators heve same error

**Comment by kevva** [comment] 2015-04-11 12:07
Duplicate of https://github.com/yeoman/yeoman/issues/1292 https://github.com/yeoman/yeoman/issues/1497. All in all, you need to fix the permissions on the `.config` folder so that `yo` can access it.

**Closed by kevva** 2015-04-11 12:07 UTC

**Comment by seoyoochan** [comment] 2015-06-16 10:43
@kevva :+1: thank you!
